server:
  host: "0.0.0.0"
  port: 8085
  static_dir: "./static"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

rabbitmq:
  host: "localhost"
  port: 5672
  username: "user"
  password: $RABBITMQ_PASSWORD
  queue_name: "delayed_notifications"

telegram:
  # Leave empty and set TELEGRAM_BOT_TOKEN env var in production.
  timeout: 30

logging:
  level: "info"
  format: "json"

kafka:
  broker: "localhost:29092"
  topic: "sent_notifications"