server:
  host: "0.0.0.0"
  port: 8080
  static_dir: "./static"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

rabbitmq:
  host: "localhost"
  port: 5672
  username: "guest"
  password: "guest"
  queue_name: "delayed_notifications"

telegram:
  bot_token: "8427335096:AAHlwt_cZ1lGIJWMY3l8Iz68E4Bs-YX_q2s"
  timeout: 30

logging:
  level: "info"
  format: "json"
