server:
  host: "0.0.0.0"
  port: 8080
  static_dir: "./static"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

rabbitmq:
  host: "localhost"
  port: 5672
  username: "guest"
  password: "guest"
  queue_name: "delayed_notifications"

telegram:
  bot_token: "YOUR_TELEGRAM_BOT_TOKEN_HERE"
  timeout: 30

logging:
  level: "info"
  format: "json"
