CREATE TABLE IF NOT EXISTS images (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	ext VARCHAR(10) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	status VARCHAR(20) NOT NULL DEFAULT 'pending'
);

