storage:
  master_dsn: "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB?sslmode=disable"
  slave_dsns:
    # - "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB?sslmode=disable"
    - 

server:
  address: ":8080"
  static_dir: "./frontend"
