CREATE TABLE IF NOT EXISTS events (
	pk BIGSERIAL PRIMARY KEY,
	id UUID NOT NULL UNIQUE,
	name VARCHAR(255) NOT NULL,
	capacity BIGINT NOT NULL,
	date TIMESTAMPTZ NOT NULL,
	payment_ttl INTERVAL NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bookings (
	id UUID PRIMARY KEY,
	event_id UUID NOT NULL REFERENCES events(id) ON DELETE CASCADE,
	user_id UUID NOT NULL,
	decremented BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	payment_deadline TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS notifications (
	id UUID NOT NULL UNIQUE,
	user_id UUID NOT NULL,
	event_id UUID NOT NULL REFERENCES events(id) ON DELETE CASCADE,
	booking_id UUID NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
	send_at TIMESTAMPTZ NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);



