services:

  commenttree:
    build: .
    container_name: commenttree
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - CONFIG_FILE=/app/config.yaml
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./static:/app/static
  postgres:
    image: postgres:17
    container_name: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: commenttree
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-commenttree} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  migrator:
    image: migrate/migrate:v4.17.1
    container_name: migrator
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migration:/migration:ro
    command:
      - -path=/migration
      - -database
      - postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/commenttree?sslmode=disable
      - up

volumes:
  postgres_data: