server:
  host: "0.0.0.0"
  port: "8085"

redis:
  host: "redis"
  port: "6379"
  password: $REDIS_PASSWORD
  db: 0

rabbitmq:
  host: "rabbitmq"
  port: "5672"
  username: "user"
  password: $RABBITMQ_PASSWORD
  queue_name: "delayed_notifications"

kafka:
  broker: "kafka:9092"
  topic: "sent_notifications"