services:
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortener
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrator:
    image: migrate/migrate:v4.17.1
    container_name: migrator
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations:ro
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        i=0; \
        until migrate -path=/migrations -database "postgres://postgres:postgres@postgres:5432/shortener?sslmode=disable" up; do \
          i=$$((i+1)); echo "migrate failed, retry $$i"; sleep 2; \
        done; \
        echo "migrations applied"

volumes:
  postgres_data: